# Generated by Django 4.1 on 2024-04-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hometimesheet",
            name="day",
            field=models.DateField(),
        ),
    ]
