# Generated by Django 4.1 on 2024-04-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0004_alter_hometimesheet_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="hometimesheet",
            name="total_salary",
            field=models.IntegerField(null=True),
        ),
    ]
