# Generated by Django 4.1 on 2024-04-17 05:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("basic_app", "0006_remove_hometimesheet_total_salary"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfileInfor",
            new_name="UserProfileInfo",
        ),
    ]
