# Generated by Django 4.1 on 2024-04-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0007_rename_userprofileinfor_userprofileinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofileinfo",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="profile_pics"),
        ),
    ]
