# Generated by Django 4.1 on 2024-04-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0011_alter_hometimesheet_chore_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hometimesheet",
            name="chore_name",
            field=models.CharField(max_length=264),
        ),
    ]
